query($owner: String!, $repo: String!, $number: Int!, $endCursor: String) {
  rateLimit {
    cost
    remaining
    resetAt
  }
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $number) {
      headRefOid
      reviewThreads(first: 100, after: $endCursor) {
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          id
          isResolved
          isOutdated
          path
          line
          originalLine
          subjectType
          firstComment: comments(first: 1) {
            nodes {
              fullDatabaseId
              author {
                login
              }
              createdAt
              url
              body
            }
          }
          latestComment: comments(last: 1) {
            nodes {
              fullDatabaseId
              author {
                login
              }
              createdAt
              url
              body
            }
          }
        }
      }
    }
  }
}
